exclude: "^$|deploy|scripts|tmp"
fail_fast: false
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: check-merge-conflict
          - id: end-of-file-fixer
          - id: check-toml

    - repo: local
      hooks:
          - id: isort
            name: formatting::isort
            entry: isort
            language: system
            types: [python]

    - repo: local
      hooks:
          - id: flake8
            name: linting::flake8
            entry: flake8
            language: system
            types: [python]

    - repo: https://github.com/aws-cloudformation/cfn-python-lint
      rev: v0.77.6  # The version of cfn-lint to use
      hooks:
        - id: cfn-python-lint
          name: linting::cloudformation
          files: aws_infrastructure.yaml
